"""Project-wide immutable experiment constants."""

FULL_LAFAN_STOP_MESSAGE = (
    "FULL-LAFAN EXPERIMENTS NOT STARTED — WAITING FOR USER APPROVAL."
)
CANONICAL_QPOS_WIDTH = 36
G1_JOINT_COUNT = 29
MIN_COMPLETION_RATIO = 0.95

